language: elixir
elixir: '1.8.0'
otp_release: '21.1.1'

env:
  - COCKROACHDB_VERSION=2.1.3

before_install:
  - curl https://binaries.cockroachdb.com/cockroach-v${COCKROACHDB_VERSION}.linux-amd64.tgz | tar -xz && cockroach-v${COCKROACHDB_VERSION}.linux-amd64/cockroach start --insecure --listen-addr=localhost --background

cache:
  directories:
    - _build
    - deps
