version: '3'

services:
  postgresql:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hammoc_prod
    ports:
      - '5432:5432'

  dgraph:
    image: dgraph/standalone
    restart: always
    ports:
      - '8000:8000'
      - '8080:8080'
      - '9080:9080'

  dgraph-test:
    image: dgraph/standalone
    restart: always
    ports:
      - '8001:8000'
      - '8081:8080'
      - '9081:9080'
